# Generated by Django 3.0.10 on 2020-09-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['student', 'month']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='term',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='session',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='class_for',
        ),
    ]
