# Generated by Django 3.1.4 on 2021-05-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_expensecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='academicterm',
            options={'ordering': ['id']},
        ),
    ]
