# Generated by Django 3.1.4 on 2021-05-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0004_auto_20210503_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('document', models.FileField(null=True, upload_to='media/documents/%Y/%m/%d/')),
            ],
        ),
    ]
