# Generated by Django 3.1.4 on 2021-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0005_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='image',
            field=models.ImageField(null=True, upload_to='Cover_images'),
        ),
    ]
