# Generated by Django 3.0.3 on 2020-04-16 15:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_description', models.TextField(max_length=100)),
                ('tag_number', models.TextField(unique=True)),                
                ('serial_number', models.TextField()),
                ('category', models.TextField(choices=[('COMPUTERS', 'COMPUTER'), ('FURNITURES', 'FURNITURE'), ('OFFICE_EQUIPMENT', 'OFFICE EQUIPMENT'), ('LINK_EQUIPMENT', 'LINK EQUIPMENT'), ('SERVERS', 'SERVERS')])),
                ('location', models.TextField(choices=[('BRANCH_1', 'BRANCH 1'), ('BRANCH_2', 'BRANCH 2'), ('BRANCH_3', 'BRANCH 3'), ('BRANCH_4', 'BRANCH 5'), ('BRANCH_5', 'BRANCH 5')])),
                ('date_in_service', models.DateField(default=datetime.date.today)),
               
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
