# Generated by Django 3.0.10 on 2020-09-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.TextField(default='None'),
        ),
    ]
