# Generated by Django 3.1.4 on 2021-06-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200921_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='voucher_number',
            field=models.TextField(null=True),
        ),
    ]
