# Generated by Django 3.1.4 on 2021-08-14 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_bulkassetupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.TextField(blank=True, choices=[('COMPUTERS', 'COMPUTER'), ('FURNITURES', 'FURNITURE'), ('OFFICE_EQUIPMENT', 'OFFICE EQUIPMENT'), ('LINK_EQUIPMENT', 'LINK EQUIPMENT'), ('SERVERS', 'SERVERS')]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_in_service',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tag_number',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='voucher_number',
            field=models.TextField(blank=True),
        ),
    ]
