# Generated by Django 3.1.4 on 2021-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20210814_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_in_service',
            field=models.TextField(blank=True),
        ),
    ]
