# Generated by Django 3.1.4 on 2021-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20210817_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.TextField(blank=True, choices=[('COMPUTERS', 'COMPUTER'), ('FURNITURES', 'FURNITURE'), ('OFFICE_EQUIPMENT', 'OFFICE EQUIPMENT'), ('LINK_EQUIPMENT', 'LINK EQUIPMENT'), ('MUSIC', 'MUSIC'), ('KITCHEN UQUIPMENT', 'KITCHEN EQUIPMENT'), ('SERVERS', 'SERVERS')]),
        ),
    ]
