# Generated by Django 3.1.4 on 2021-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20210817_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.TextField(choices=[('IN_USE', 'IN_USE'), ('DISPOSED', 'DISPOSED')], default='IN_USE'),
        ),
    ]
