# Generated by Django 3.1 on 2020-09-04 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('location', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('location', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=50)),
                ('second_name', models.TextField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.TextField(max_length=20)),
                ('first_name', models.TextField(max_length=50)),
                ('second_name', models.TextField(max_length=50)),
                ('surname', models.TextField(max_length=50)),
                ('photo', models.ImageField(upload_to='student_images')),
                ('school', models.TextField(max_length=200)),
                ('location', models.TextField(max_length=150)),
                ('level', models.TextField(choices=[('STD 1', 'STD 1'), ('STD 2', 'STD 2'), ('STD 3', 'STD 3'), ('STD 4', 'STD 4'), ('STD 5', 'STD 5'), ('STD 6', 'STD 6'), ('STD 7', 'STD 7'), ('STD 8', 'STD 8'), ('FORM 1', 'FORM 1'), ('FORM 2', 'FORM 2'), ('FORM 3', 'FORM 3'), ('FORM 4', 'FORM 4')])),
                ('talent', models.TextField(max_length=300)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.centre')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parent')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.church')),
            ],
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('photos', models.ImageField(upload_to='homevisit_images')),
                ('report', models.CharField(max_length=500, null=True)),
                ('staff_to_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.AddField(
            model_name='centre',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.church'),
        ),
        migrations.AddField(
            model_name='centre',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
