# Generated by Django 3.1 on 2020-09-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevisit',
            name='status',
            field=models.TextField(choices=[('ongoing', 'ongoing'), ('completed', 'completed')], default='ongoing'),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='photos',
            field=models.ImageField(null=True, upload_to='homevisit_images'),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='report',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
