# Generated by Django 3.1 on 2020-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_finance_gift_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='gift',
            name='status',
            field=models.TextField(choices=[('not_collected', 'not_collected'), ('collected', 'collected')], default='not_collected'),
        ),
    ]
