# Generated by Django 3.0.10 on 2020-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
