# Generated by Django 3.0.10 on 2020-09-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_finance_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='total',
        ),
    ]
