# Generated by Django 3.0.10 on 2020-09-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200906_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.TextField(max_length=13),
        ),
    ]
