# Generated by Django 3.0.10 on 2020-09-06 21:06

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200906_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomevisitImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.visit_directory_path)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HomeVisit')),
            ],
        ),
    ]
