# Generated by Django 3.0.10 on 2020-09-08 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_homevisitimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homevisit',
            name='photos',
        ),
        migrations.AddField(
            model_name='parent',
            name='occupation',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_to', to='main.Student'),
        ),
        migrations.AlterField(
            model_name='homevisitimages',
            name='image',
            field=models.ImageField(upload_to='homevisit_images'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='not_approved', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
