# Generated by Django 3.0.10 on 2020-09-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200908_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
