# Generated by Django 3.0.10 on 2020-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200908_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_baptism',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_dedication',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsor_status',
            field=models.TextField(choices=[('self_sponsored', 'self_sponsored'), ('cdc_sponsored', 'cdc_sponsored')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.TextField(choices=[('village 1', 'village 1'), ('village 2', 'village 2'), ('village 3', 'village 3')], null=True),
        ),
    ]
