# Generated by Django 3.0.10 on 2020-09-09 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20200908_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homevisit',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': ((('can_only_view_teaching_student', 'can_only_view_teaching_student'), ('church_details', 'church_details')),)},
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
