# Generated by Django 3.0.10 on 2020-09-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200909_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_only_view_teaching_student', 'can_only_view_teaching_student'),)},
        ),
    ]
