# Generated by Django 3.0.10 on 2020-09-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200909_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finance',
            new_name='Finance1',
        ),
    ]
