# Generated by Django 3.0.10 on 2020-09-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200910_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_to',
        ),
    ]
