# Generated by Django 3.0.10 on 2020-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_parent_parent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='exam_type',
            field=models.TextField(choices=[('FIRST_TERM', 'FIRST TERM'), ('SECOND_TERM', 'SECOND TERM'), ('THIRD_TERM', 'THIRD TERM')], null=True),
        ),
    ]
