# Generated by Django 3.0.10 on 2020-09-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_performance_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='number_of_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='remaining_days',
            field=models.IntegerField(null=True),
        ),
    ]
