# Generated by Django 3.0.10 on 2020-09-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200910_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='remaining_days',
        ),
        migrations.AlterField(
            model_name='student',
            name='centre',
            field=models.TextField(default='CTM MURUMBA', null=True),
        ),
        migrations.DeleteModel(
            name='Centre',
        ),
    ]
