# Generated by Django 3.0.10 on 2020-09-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200918_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.TextField(max_length=20),
        ),
    ]
