# Generated by Django 3.1.4 on 2021-05-11 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_auto_20200918_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='church',
            name='location',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_type',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.TextField(default='not_approved', max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='second_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_baptism',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_dedication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='student_images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_status',
            field=models.TextField(blank=True, choices=[('self_sponsored', 'self_sponsored'), ('cdc_sponsored', 'cdc_sponsored')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='talent',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='village',
            field=models.TextField(blank=True, null=True),
        ),
    ]
