# Generated by Django 3.1.4 on 2021-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210511_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='centre',
            field=models.TextField(default='ACK BUDOKOMI CDC', null=True),
        ),
    ]
