# Generated by Django 3.1.4 on 2021-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210902_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkStudentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='student/bulkupload/')),
            ],
        ),
    ]
