# Generated by Django 3.1.4 on 2021-09-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_bulkstudentupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
    ]
