# Generated by Django 3.1.4 on 2021-09-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_student_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sponsor',
        ),
    ]
