# Generated by Django 3.1.4 on 2021-09-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210902_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
